#!/usr/bin/env python3
"""
Run LLM grading for benchmark iterations generated by setup_benchmark.py.

This runner invokes `codex exec` once per run directory and asks the grader to
write `grading.json` in place. The canonical grading unit is a single run:

- eval-N/with_skill/run-K
- eval-N/without_skill/run-K or eval-N/old_skill/run-K

The runner records:
- grading_prompt.md
- grader-events.jsonl
- grader-stderr.log
- grading_provenance.json
- timing.json (updated with grader_* fields)
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from collections import deque
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import BinaryIO

try:
    from scripts.utils import apply_codex_model_settings
except ModuleNotFoundError:
    from utils import apply_codex_model_settings


UTF8 = "utf-8"
DEFAULT_MODEL = "gpt-5.4-mini"
DEFAULT_SANDBOX = "workspace-write"
DEFAULT_MAX_CONCURRENCY = 6
DEFAULT_POLL_INTERVAL = 0.5
CONFIG_PRIORITY = {
    "with_skill": 0,
    "without_skill": 1,
    "old_skill": 1,
}
VALID_CLAIM_TYPES = {"factual", "process", "quality"}


def read_json_utf8(path: Path) -> dict:
    with path.open(encoding=UTF8) as handle:
        payload = json.load(handle)
    if not isinstance(payload, dict):
        raise ValueError(f"Expected a JSON object in {path}")
    return payload


def write_json_utf8(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding=UTF8) as handle:
        json.dump(data, handle, indent=2, ensure_ascii=False)
        handle.write("\n")


def write_text_utf8(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding=UTF8)


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def isoformat_utc(value: datetime) -> str:
    return value.strftime("%Y-%m-%dT%H:%M:%SZ")


def parse_numeric_suffix(path: Path, prefix: str) -> int:
    if not path.name.startswith(prefix):
        raise ValueError(f"Expected name starting with '{prefix}': {path.name}")
    suffix = path.name[len(prefix):]
    return int(suffix)


def config_sort_key(name: str) -> tuple[int, str]:
    return (CONFIG_PRIORITY.get(name, 9), name)


def validate_max_concurrency(value: int) -> int:
    if value < 1:
        raise ValueError("max_concurrency must be at least 1")
    return value


def validate_poll_interval(value: float) -> float:
    if value <= 0:
        raise ValueError("poll_interval must be greater than 0")
    return value


def resolve_codex_bin(command: str) -> str:
    resolved = shutil.which(command)
    if resolved:
        return resolved

    path = Path(command)
    if path.exists():
        return str(path.resolve())

    raise FileNotFoundError(f"Unable to resolve codex executable: {command}")


def build_codex_command(
    codex_bin: str,
    run_dir: Path,
    model: str,
    reasoning_effort: str | None,
    sandbox: str,
) -> tuple[list[str], str | None]:
    command = [codex_bin, "exec", "-"]
    resolved_reasoning_effort = apply_codex_model_settings(command, model, reasoning_effort)
    command.extend(
        [
            "--cd",
            str(run_dir),
            "--sandbox",
            sandbox,
            "--skip-git-repo-check",
            "--json",
            "--ephemeral",
        ]
    )
    return command, resolved_reasoning_effort


def infer_baseline(iteration_dir: Path, metadata: dict) -> str:
    baseline = metadata.get("baseline")
    if isinstance(baseline, str) and baseline:
        return baseline

    sample_eval = next((path for path in sorted(iteration_dir.glob("eval-*")) if path.is_dir()), None)
    if sample_eval is None:
        raise FileNotFoundError(f"No eval directories found in {iteration_dir}")

    config_dirs = {
        path.name
        for path in sample_eval.iterdir()
        if path.is_dir() and any(child.is_dir() for child in path.glob("run-*"))
    }
    for candidate in ("without_skill", "old_skill"):
        if candidate in config_dirs:
            return candidate

    raise ValueError(f"Unable to infer baseline config in {sample_eval}")


def load_grader_instructions() -> str:
    skill_root = Path(__file__).resolve().parents[1]
    grader_path = skill_root / "agents" / "grader.md"
    return grader_path.read_text(encoding=UTF8)


def load_optional_json(path: Path) -> dict:
    if not path.exists():
        return {}
    return read_json_utf8(path)


def update_timing_with_grader(
    timing_path: Path,
    grader_start: datetime,
    grader_end: datetime,
    grader_duration_seconds: float,
) -> dict:
    timing = load_optional_json(timing_path)
    timing["grader_start"] = isoformat_utc(grader_start)
    timing["grader_end"] = isoformat_utc(grader_end)
    timing["grader_duration_seconds"] = round(grader_duration_seconds, 3)
    write_json_utf8(timing_path, timing)
    return timing


def normalize_execution_metrics(raw_metrics: object, metrics_path: Path) -> dict:
    metrics = raw_metrics if isinstance(raw_metrics, dict) else {}
    if not metrics and metrics_path.exists():
        metrics = read_json_utf8(metrics_path)

    tool_calls = metrics.get("tool_calls", {})
    normalized_tool_calls = tool_calls if isinstance(tool_calls, dict) else {}

    def int_value(name: str) -> int:
        value = metrics.get(name, 0)
        return value if isinstance(value, int) and not isinstance(value, bool) else 0

    return {
        "tool_calls": normalized_tool_calls,
        "total_tool_calls": int_value("total_tool_calls"),
        "total_steps": int_value("total_steps"),
        "errors_encountered": int_value("errors_encountered"),
        "output_chars": int_value("output_chars"),
        "transcript_chars": int_value("transcript_chars"),
    }


def normalize_claims(raw_claims: object) -> list[dict]:
    if not isinstance(raw_claims, list):
        return []

    claims: list[dict] = []
    for item in raw_claims:
        if not isinstance(item, dict):
            continue
        claim = item.get("claim")
        claim_type = item.get("type")
        verified = item.get("verified")
        evidence = item.get("evidence")
        if not isinstance(claim, str) or not claim.strip():
            continue
        if claim_type not in VALID_CLAIM_TYPES:
            continue
        if not isinstance(verified, bool):
            continue
        if not isinstance(evidence, str) or not evidence.strip():
            continue
        claims.append(
            {
                "claim": claim.strip(),
                "type": claim_type,
                "verified": verified,
                "evidence": evidence.strip(),
            }
        )
    return claims


def normalize_string_list(value: object) -> list[str]:
    if not isinstance(value, list):
        return []
    return [item.strip() for item in value if isinstance(item, str) and item.strip()]


def normalize_user_notes_summary(raw_summary: object) -> dict:
    summary = raw_summary if isinstance(raw_summary, dict) else {}
    return {
        "uncertainties": normalize_string_list(summary.get("uncertainties", [])),
        "needs_review": normalize_string_list(summary.get("needs_review", [])),
        "workarounds": normalize_string_list(summary.get("workarounds", [])),
    }


def normalize_eval_feedback(raw_feedback: object) -> dict:
    feedback = raw_feedback if isinstance(raw_feedback, dict) else {}
    raw_suggestions = feedback.get("suggestions", [])
    suggestions: list[dict] = []
    if isinstance(raw_suggestions, list):
        for item in raw_suggestions:
            if not isinstance(item, dict):
                continue
            reason = item.get("reason")
            if not isinstance(reason, str) or not reason.strip():
                continue
            normalized = {"reason": reason.strip()}
            assertion = item.get("assertion")
            if isinstance(assertion, str) and assertion.strip():
                normalized["assertion"] = assertion.strip()
            suggestions.append(normalized)

    overall = feedback.get("overall")
    if not isinstance(overall, str) or not overall.strip():
        overall = "No suggestions, evals look solid"

    return {
        "suggestions": suggestions,
        "overall": overall.strip(),
    }


def normalize_expectations(raw_expectations: object, expected_texts: list[str]) -> list[dict]:
    if not isinstance(raw_expectations, list):
        raise ValueError("grading.json is missing an 'expectations' array")
    if len(raw_expectations) != len(expected_texts):
        raise ValueError(
            f"grading.json expectations length mismatch: expected {len(expected_texts)}, got {len(raw_expectations)}"
        )

    normalized: list[dict] = []
    for index, expected_text in enumerate(expected_texts):
        item = raw_expectations[index]
        if not isinstance(item, dict):
            raise ValueError(f"Expectation #{index + 1} is not a JSON object")

        passed = item.get("passed")
        evidence = item.get("evidence")
        if not isinstance(passed, bool):
            raise ValueError(f"Expectation #{index + 1} is missing boolean 'passed'")
        if not isinstance(evidence, str) or not evidence.strip():
            raise ValueError(f"Expectation #{index + 1} is missing non-empty 'evidence'")

        normalized.append(
            {
                "text": expected_text,
                "passed": passed,
                "evidence": evidence.strip(),
            }
        )

    return normalized


def summarize_expectations(expectations: list[dict]) -> dict:
    passed = sum(1 for item in expectations if item["passed"])
    total = len(expectations)
    failed = total - passed
    pass_rate = round((passed / total), 4) if total else 0.0
    return {
        "passed": passed,
        "failed": failed,
        "total": total,
        "pass_rate": pass_rate,
    }


@dataclass(frozen=True)
class GradeSpec:
    eval_id: int
    eval_name: str
    eval_prompt: str
    expected_output: str
    assertions: tuple[str, ...]
    config: str
    run_number: int
    run_dir: Path
    baseline_type: str

    @property
    def label(self) -> str:
        return f"eval-{self.eval_id}/{self.config}/run-{self.run_number}"

    @property
    def outputs_dir(self) -> Path:
        return self.run_dir / "outputs"

    @property
    def transcript_candidates(self) -> tuple[Path, ...]:
        return (
            self.run_dir / "transcript.md",
            self.outputs_dir / "transcript.md",
        )

    @property
    def grading_path(self) -> Path:
        return self.run_dir / "grading.json"

    @property
    def grading_prompt_path(self) -> Path:
        return self.run_dir / "grading_prompt.md"

    @property
    def grader_events_path(self) -> Path:
        return self.run_dir / "grader-events.jsonl"

    @property
    def grader_stderr_path(self) -> Path:
        return self.run_dir / "grader-stderr.log"

    @property
    def grading_provenance_path(self) -> Path:
        return self.run_dir / "grading_provenance.json"

    @property
    def timing_path(self) -> Path:
        return self.run_dir / "timing.json"


@dataclass
class ActiveGrade:
    spec: GradeSpec
    command: list[str]
    resolved_reasoning_effort: str | None
    process: subprocess.Popen[bytes]
    prompt_handle: BinaryIO
    stdout_handle: BinaryIO
    stderr_handle: BinaryIO
    start_dt: datetime
    start_perf: float


@dataclass(frozen=True)
class CompletedGrade:
    spec: GradeSpec
    returncode: int
    duration_seconds: float
    valid_output: bool
    error: str | None = None


def build_grading_prompt(spec: GradeSpec, grader_instructions: str) -> str:
    expectations_json = json.dumps(list(spec.assertions), indent=2, ensure_ascii=False)
    transcript_candidates = "\n".join(
        f"- `{candidate.relative_to(spec.run_dir).as_posix()}`"
        for candidate in spec.transcript_candidates
    )

    run_context = {
        "eval_id": spec.eval_id,
        "eval_name": spec.eval_name,
        "configuration": spec.config,
        "run_number": spec.run_number,
        "baseline_type": spec.baseline_type,
        "eval_prompt": spec.eval_prompt,
        "expected_output": spec.expected_output,
        "expectations": list(spec.assertions),
    }

    return "\n".join(
        [
            "당신은 codex-skill-creator benchmark의 run 단위 LLM grader입니다.",
            "현재 작업 디렉터리는 정확히 하나의 benchmark run 디렉터리입니다.",
            "다른 eval이나 다른 run은 보지 말고, 현재 run의 transcript와 outputs만 근거로 판정하세요.",
            "기존 benchmark 산출물은 수정하지 말고, 오직 `grading.json`만 작성하거나 덮어쓰세요.",
            "",
            "# Canonical Grader Instructions",
            grader_instructions.strip(),
            "",
            "# Run Context",
            "```json",
            json.dumps(run_context, indent=2, ensure_ascii=False),
            "```",
            "",
            "# Available Paths (relative to cwd)",
            "- `outputs/`",
            "- `outputs/metrics.json` (optional)",
            "- `outputs/user_notes.md` (optional)",
            "- `timing.json` (optional executor timing)",
            "- `codex-events.jsonl` (optional executor event log)",
            "- `codex-stderr.log` (optional executor stderr log)",
            "- `../eval_metadata.json`",
            "- transcript candidates:",
            transcript_candidates,
            "",
            "# Output Contract",
            "- Write one UTF-8 JSON object to `grading.json`.",
            "- The `expectations` array must have the same length and order as the provided expectations.",
            "- Each expectation object must use exactly `text`, `passed`, `evidence`.",
            "- Use the exact expectation strings below as the source of truth for `text`:",
            "```json",
            expectations_json,
            "```",
            "- If evidence is missing or ambiguous, mark the expectation as failed instead of guessing.",
            "- Do not include Markdown fences or the JSON body in the final chat response.",
            "- Final chat response should be a short confirmation that `grading.json` was written.",
        ]
    )


def is_gradeable_run(run_dir: Path) -> bool:
    return (run_dir / "timing.json").exists()


def load_and_normalize_grading(spec: GradeSpec) -> dict:
    raw_grading = read_json_utf8(spec.grading_path)
    normalized_expectations = normalize_expectations(raw_grading.get("expectations"), list(spec.assertions))
    summary = summarize_expectations(normalized_expectations)
    timing = load_optional_json(spec.timing_path)
    metrics = normalize_execution_metrics(raw_grading.get("execution_metrics"), spec.outputs_dir / "metrics.json")

    return {
        "expectations": normalized_expectations,
        "summary": summary,
        "execution_metrics": metrics,
        "timing": timing,
        "claims": normalize_claims(raw_grading.get("claims")),
        "user_notes_summary": normalize_user_notes_summary(raw_grading.get("user_notes_summary")),
        "eval_feedback": normalize_eval_feedback(raw_grading.get("eval_feedback")),
    }


def has_valid_grading(spec: GradeSpec) -> bool:
    if not spec.grading_path.exists():
        return False

    try:
        load_and_normalize_grading(spec)
    except Exception:
        return False

    return True


def discover_grade_specs(
    iteration_dir: Path,
    resume: bool,
    eval_filter: set[int] | None,
    config_filter: set[str] | None,
    run_filter: set[int] | None,
) -> list[GradeSpec]:
    metadata_path = iteration_dir / "iteration_metadata.json"
    metadata = read_json_utf8(metadata_path) if metadata_path.exists() else {}
    baseline = infer_baseline(iteration_dir, metadata)

    specs: list[GradeSpec] = []
    eval_dirs = sorted(
        (path for path in iteration_dir.glob("eval-*") if path.is_dir()),
        key=lambda path: parse_numeric_suffix(path, "eval-"),
    )
    if not eval_dirs:
        raise FileNotFoundError(f"No eval directories found in {iteration_dir}")

    for eval_dir in eval_dirs:
        eval_metadata_path = eval_dir / "eval_metadata.json"
        eval_metadata = read_json_utf8(eval_metadata_path) if eval_metadata_path.exists() else {}
        eval_id = int(eval_metadata.get("eval_id", parse_numeric_suffix(eval_dir, "eval-")))
        if eval_filter and eval_id not in eval_filter:
            continue

        assertions = eval_metadata.get("assertions", [])
        if not isinstance(assertions, list) or any(not isinstance(item, str) for item in assertions):
            raise ValueError(f"Invalid or missing assertions in {eval_metadata_path}")

        config_dirs = sorted(
            (
                path for path in eval_dir.iterdir()
                if path.is_dir() and any(child.is_dir() for child in path.glob("run-*"))
            ),
            key=lambda path: config_sort_key(path.name),
        )

        for config_dir in config_dirs:
            config_name = config_dir.name
            if config_filter and config_name not in config_filter:
                continue

            for run_dir in sorted(config_dir.glob("run-*"), key=lambda path: parse_numeric_suffix(path, "run-")):
                if not run_dir.is_dir() or not is_gradeable_run(run_dir):
                    continue
                run_number = parse_numeric_suffix(run_dir, "run-")
                if run_filter and run_number not in run_filter:
                    continue

                spec = GradeSpec(
                    eval_id=eval_id,
                    eval_name=str(eval_metadata.get("eval_name", f"eval-{eval_id}")),
                    eval_prompt=str(eval_metadata.get("prompt", "")),
                    expected_output=str(eval_metadata.get("expected_output", "")),
                    assertions=tuple(assertions),
                    config=config_name,
                    run_number=run_number,
                    run_dir=run_dir,
                    baseline_type=baseline,
                )
                if resume and has_valid_grading(spec):
                    continue
                specs.append(spec)

    specs.sort(key=lambda item: (item.run_number, item.eval_id, config_sort_key(item.config)))
    return specs


def write_grading_provenance(
    spec: GradeSpec,
    command: list[str],
    model: str | None,
    reasoning_effort: str | None,
    exit_code: int | None,
    status: str,
    prompt_path: Path,
    error: str | None = None,
) -> None:
    payload = {
        "executor": "codex exec",
        "configuration": spec.config,
        "baseline_type": spec.baseline_type,
        "prompt_path": str(prompt_path),
        "grading_path": str(spec.grading_path),
        "command": command,
        "model": model,
        "reasoning_effort": reasoning_effort,
        "events_path": str(spec.grader_events_path),
        "stderr_path": str(spec.grader_stderr_path),
        "exit_code": exit_code,
        "status": status,
        "recorded_at": isoformat_utc(utc_now()),
    }
    if error:
        payload["error"] = error
    write_json_utf8(spec.grading_provenance_path, payload)


def write_launch_failure(spec: GradeSpec, error: Exception, command: list[str]) -> None:
    now = utc_now()
    update_timing_with_grader(
        timing_path=spec.timing_path,
        grader_start=now,
        grader_end=now,
        grader_duration_seconds=0.0,
    )
    write_grading_provenance(
        spec=spec,
        command=command,
        model=None,
        reasoning_effort=None,
        exit_code=-1,
        status="launch_failed",
        prompt_path=spec.grading_prompt_path,
        error=str(error),
    )


def launch_grade(
    spec: GradeSpec,
    grader_instructions: str,
    codex_bin: str,
    model: str,
    reasoning_effort: str | None,
    sandbox: str,
) -> ActiveGrade:
    prompt = build_grading_prompt(spec, grader_instructions)
    write_text_utf8(spec.grading_prompt_path, prompt)

    command, resolved_reasoning_effort = build_codex_command(
        codex_bin=codex_bin,
        run_dir=spec.run_dir,
        model=model,
        reasoning_effort=reasoning_effort,
        sandbox=sandbox,
    )

    prompt_handle = spec.grading_prompt_path.open("rb")
    stdout_handle = spec.grader_events_path.open("wb")
    stderr_handle = spec.grader_stderr_path.open("wb")
    start_dt = utc_now()
    start_perf = time.perf_counter()

    try:
        process = subprocess.Popen(
            command,
            stdin=prompt_handle,
            stdout=stdout_handle,
            stderr=stderr_handle,
            cwd=spec.run_dir,
        )
    except Exception as error:
        prompt_handle.close()
        stdout_handle.close()
        stderr_handle.close()
        write_launch_failure(spec, error, command)
        raise

    return ActiveGrade(
        spec=spec,
        command=command,
        resolved_reasoning_effort=resolved_reasoning_effort,
        process=process,
        prompt_handle=prompt_handle,
        stdout_handle=stdout_handle,
        stderr_handle=stderr_handle,
        start_dt=start_dt,
        start_perf=start_perf,
    )


def finalize_grade(active_grade: ActiveGrade) -> CompletedGrade:
    returncode = active_grade.process.wait()
    end_dt = utc_now()
    elapsed_seconds = max(time.perf_counter() - active_grade.start_perf, 0.0)

    active_grade.prompt_handle.close()
    active_grade.stdout_handle.close()
    active_grade.stderr_handle.close()

    update_timing_with_grader(
        timing_path=active_grade.spec.timing_path,
        grader_start=active_grade.start_dt,
        grader_end=end_dt,
        grader_duration_seconds=elapsed_seconds,
    )

    error: str | None = None
    valid_output = False
    try:
        normalized = load_and_normalize_grading(active_grade.spec)
        write_json_utf8(active_grade.spec.grading_path, normalized)
        valid_output = True
    except Exception as exc:
        error = str(exc)

    status = "completed"
    if not valid_output:
        status = "invalid_output"
    elif returncode != 0:
        status = "completed_with_nonzero_exit"

    model = next(
        (active_grade.command[index + 1] for index, value in enumerate(active_grade.command[:-1]) if value == "--model"),
        None,
    )
    write_grading_provenance(
        spec=active_grade.spec,
        command=active_grade.command,
        model=model,
        reasoning_effort=active_grade.resolved_reasoning_effort,
        exit_code=returncode,
        status=status,
        prompt_path=active_grade.spec.grading_prompt_path,
        error=error,
    )

    return CompletedGrade(
        spec=active_grade.spec,
        returncode=returncode,
        duration_seconds=elapsed_seconds,
        valid_output=valid_output,
        error=error,
    )


def print_queue_plan(specs: list[GradeSpec]) -> None:
    print(f"Queued {len(specs)} grading run(s):")
    for spec in specs:
        print(f"  {spec.label}")


def run_grades(
    specs: list[GradeSpec],
    grader_instructions: str,
    codex_bin: str,
    model: str,
    reasoning_effort: str | None,
    sandbox: str,
    max_concurrency: int,
    poll_interval: float,
) -> list[CompletedGrade]:
    pending = deque(specs)
    active: list[ActiveGrade] = []
    completed: list[CompletedGrade] = []

    while pending or active:
        finished: list[ActiveGrade] = []
        for active_grade in active:
            if active_grade.process.poll() is not None:
                finished.append(active_grade)

        for active_grade in finished:
            active.remove(active_grade)
            result = finalize_grade(active_grade)
            completed.append(result)
            if result.valid_output:
                status = "ok" if result.returncode == 0 else f"ok(exit={result.returncode})"
            else:
                status = f"invalid ({result.error})"
            print(f"Completed {result.spec.label} in {result.duration_seconds:.2f}s ({status})")

        while pending and len(active) < max_concurrency:
            spec = pending.popleft()
            print(f"Launching grader for {spec.label}")
            active.append(
                launch_grade(
                    spec=spec,
                    grader_instructions=grader_instructions,
                    codex_bin=codex_bin,
                    model=model,
                    reasoning_effort=reasoning_effort,
                    sandbox=sandbox,
                )
            )

        if active:
            time.sleep(poll_interval)

    return completed


def parse_filter_values(values: list[str] | None, label: str) -> set[int] | None:
    if not values:
        return None
    parsed: set[int] = set()
    for value in values:
        try:
            parsed.add(int(value))
        except ValueError as exc:
            raise ValueError(f"Invalid {label} value '{value}'; expected integers") from exc
    return parsed


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run LLM grading for benchmark iteration runs"
    )
    parser.add_argument(
        "iteration_dir",
        type=Path,
        help="Path to the iteration directory created by setup_benchmark.py",
    )
    parser.add_argument(
        "--codex-bin",
        default="codex",
        help="Codex executable to invoke (default: codex)",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"Model to use for codex exec (default: {DEFAULT_MODEL})",
    )
    parser.add_argument(
        "--reasoning-effort",
        help="Optional reasoning effort override passed to Codex",
    )
    parser.add_argument(
        "--sandbox",
        default=DEFAULT_SANDBOX,
        choices=("read-only", "workspace-write", "danger-full-access"),
        help=f"Sandbox mode for codex exec (default: {DEFAULT_SANDBOX})",
    )
    parser.add_argument(
        "--max-concurrency",
        type=int,
        default=DEFAULT_MAX_CONCURRENCY,
        help=f"Maximum number of live codex exec grader processes (default: {DEFAULT_MAX_CONCURRENCY})",
    )
    parser.add_argument(
        "--poll-interval",
        type=float,
        default=DEFAULT_POLL_INTERVAL,
        help=f"Seconds between polling active graders (default: {DEFAULT_POLL_INTERVAL})",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Skip runs that already have a valid grading.json",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the planned grading queue without launching codex exec",
    )
    parser.add_argument(
        "--eval-id",
        action="append",
        help="Only grade matching eval ids (repeatable)",
    )
    parser.add_argument(
        "--config",
        action="append",
        help="Only grade matching config names (repeatable)",
    )
    parser.add_argument(
        "--run-number",
        action="append",
        help="Only grade matching run numbers (repeatable)",
    )

    args = parser.parse_args()

    try:
        iteration_dir = args.iteration_dir.resolve()
        if not iteration_dir.exists():
            raise FileNotFoundError(f"Iteration directory not found: {iteration_dir}")

        eval_filter = parse_filter_values(args.eval_id, "eval-id")
        run_filter = parse_filter_values(args.run_number, "run-number")
        config_filter = set(args.config) if args.config else None
        max_concurrency = validate_max_concurrency(args.max_concurrency)
        poll_interval = validate_poll_interval(args.poll_interval)
        codex_bin = resolve_codex_bin(args.codex_bin)
        grader_instructions = load_grader_instructions()
        specs = discover_grade_specs(
            iteration_dir=iteration_dir,
            resume=args.resume,
            eval_filter=eval_filter,
            config_filter=config_filter,
            run_filter=run_filter,
        )
    except Exception as error:
        print(f"Error: {error}")
        sys.exit(1)

    if not specs:
        print("No pending grading runs found.")
        return

    print_queue_plan(specs)
    if args.dry_run:
        return

    try:
        completed = run_grades(
            specs=specs,
            grader_instructions=grader_instructions,
            codex_bin=codex_bin,
            model=args.model,
            reasoning_effort=args.reasoning_effort,
            sandbox=args.sandbox,
            max_concurrency=max_concurrency,
            poll_interval=poll_interval,
        )
    except Exception as error:
        print(f"Error: {error}")
        sys.exit(1)

    successes = sum(1 for item in completed if item.valid_output)
    failures = len(completed) - successes
    print("")
    print("Grading summary:")
    print(f"  Completed graders: {len(completed)}")
    print(f"  Valid outputs:     {successes}")
    print(f"  Invalid outputs:   {failures}")
    if failures:
        sys.exit(1)


if __name__ == "__main__":
    main()
